-- Top transactions by amount
SELECT 
    ft.TRANSACTION_ID,
    ft.CUSTOMER_ID,
    dm.MERCHANT_NAME,
    ft.AMOUNT,
    ft.TRANSACTION_DATE,
    ft.STATUS
FROM FACT_TRANSACTIONS ft
INNER JOIN DIM_MERCHANT dm ON ft.MERCHANT_ID = dm.MERCHANT_ID
WHERE ft.STATUS = 'COMPLETED'
ORDER BY ft.AMOUNT DESC
LIMIT 100
