"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:56:14.156340+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", current_timestamp())
                       .withColumn("source_file", lit(os.path.basename(input_path)))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode('overwrite').partitionBy('transaction_date').parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path)
                       .where(col("transaction_date") == run_date)
                        .cache())
    
    # Read merchants data and cache it
    merchants_df = (spark.read.option("header", "true")
                    .csv(merchants_path)
                     .withColumn("merchant_id", col("merchant_id").cast(StringType()))
                    .cache())
    
    # Cast columns to correct types
    transactions_df = (transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                        .withColumn("transaction_date", col("transaction_date").cast(DateType()))
                       .withColumn("transaction_id", col("transaction_id").cast(StringType()))
                       .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    
    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    deduped_transactions_df = (transactions_df.orderBy(col("transaction_id"), col("ingestion_timestamp").desc())
                               .dropDuplicates(["transaction_id"]))
    
    # Enrich: join transactions with merchants on merchant_id to get merchant_name, category, city
    enriched_transactions_df = (deduped_transactions_df.join(broadcast(merchants_df), deduped_transactions_df.merchant_id == merchants_df.merchant_id, "left_outer")
                               .withColumn("quality_flag", 
                                           when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN")))
    
    # Write as Parquet partitioned by date
    enriched_transactions_df.write.mode('overwrite').partitionBy('transaction_date').parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://sigma-datatech/bronze/transactions.csv"
    merchants_path = "s3://sigma-datatech/bronze/merchants.csv"
    bronze_path = "s3://sigma-datatech/silver/transactions"
    silver_path = "s3://sigma-datatech/silver/transactions"
    run_date = "2026-05-27"
    run_id = "run_20260527"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, bronze_path, merchants_path, silver_path, run_date)
    
    # Write run metadata summary to a JSON file
    run_metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://sigma-datatech/metadata/run_{run_id}.json", "w") as f:
        json.dump(run_metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, coalesce, avg, collect_set, lit, to_date
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate total revenue, transaction count, and failure rate
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write to Gold layer
    merchant_performance_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Calculate LTV metrics
    customer_ltv_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            coalesce(collect_set("payment_method").agg()).alias("preferred_payment_method")
        )
    
    # Write to Gold layer
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data for the specific date
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate daily summary metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(distinct("customer_id")).alias("unique_customers"),
            count(distinct("merchant_id")).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write to Gold layer
    daily_summary_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths for each Gold table
    merchant_performance_output_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_output_path = f"{gold_output_dir}/daily_summary"
    
    # Build each Gold table
    build_merchant_performance(spark, silver_path, merchant_performance_output_path, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_output_path)
    build_daily_summary(spark, silver_path, daily_summary_output_path, run_date)
    
    # Write run metadata summary to JSON
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "tables": [
            {"name": "merchant_performance", "path": merchant_performance_output_path},
            {"name": "customer_ltv", "path": customer_ltv_output_path},
            {"name": "daily_summary", "path": daily_summary_output_path}
        ]
    }
    
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata.json")

# Initialize Spark session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
