"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:51:56.763322+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, input_file_name, lit, max, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw transaction data from CSV
    raw_transactions = (spark.read.format("csv")
                        .option("header", "true")
                         .option("inferSchema", "false")
                         .load(input_path))

    # Add metadata columns and current timestamp
    enriched_transactions = (raw_transactions.withColumn("ingestion_timestamp", current_timestamp())
                             .withColumn("source_file", input_file_name())
                             .withColumn("pipeline_run_id", lit(run_id)))

    # Write to Bronze layer partitioned by date
    enriched_transactions.write.mode("append").partitionBy("load_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze layer with partition pruning
    bronze_transactions = (spark.read.format("parquet")
                           .load(bronze_path)
                          .where(col("load_date") == run_date))

    # Cast columns to correct types
    silver_transactions = (bronze_transactions.withColumn("amount", col("amount").cast(FloatType()))
                          .withColumn("transaction_date", col("transaction_date").cast(DateType())))

    # Filter NULL transaction_id and negative amounts
    silver_transactions = silver_transactions.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))

    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    silver_transactions = (silver_transactions.withColumn("rank", 
                                                         max("ingestion_timestamp").over(windowSpec))
                          .where(col("rank") == 1)
                          .drop("rank"))

    # Read merchants data, broadcast and cache it
    merchants = (spark.read.format("parquet").load(merchants_path)
                .hint("broadcast")
                .cache())

    # Join with merchants
    joined_transactions = (silver_transactions.join(broadcast(merchants), on="merchant_id", how="left"))

    # Add quality_flag column
    joined_transactions = (joined_transactions.withColumn("quality_flag", 
                                                         when(col("merchant_id").isNotNull(), "CLEAN")
                                                        .otherwise("UNMATCHED")))

    # Write to Silver layer partitioned by date
    joined_transactions.write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Customer Segmentation Pipeline")
             .getOrCreate())

    # Define paths and run parameters
    input_path = "s3://path/to/bronze/input"
    output_path_bronze = "s3://path/to/bronze/output"
    output_path_silver = "s3://path/to/silver/output"
    run_date = "2023-04-01"
    run_id = "run_id_12345"

    # Execute Bronze layer ingestion
    ingest_bronze(spark, input_path, output_path_bronze, run_date, run_id)

    # Define merchants path
    merchants_path = "s3://path/to/merchants/dim"

    # Execute Silver layer transformation
    transform_silver(spark, output_path_bronze, merchants_path, output_path_silver, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, min, expr, when, coalesce
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read the silver layer data
    silver_df = spark.read.format("delta").load(silver_path)
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate metrics
    merchant_performance_df = completed_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write the output
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path):
    # Read the silver layer data
    silver_df = spark.read.format("delta").load(silver_path)
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate metrics
    customer_ltv_df = completed_df.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            max("txn_date").alias("last_txn_date"),
            min("txn_date").alias("first_txn_date"),
            coalesce(expr("mode(payment_method)"), lit(None)).alias("preferred_payment_method")
        )
    
    # Calculate average transaction value
    customer_ltv_df = customer_ltv_df.withColumn("avg_txn_value", col("total_spent") / col("total_txns"))
    
    # Write the output
    customer_ltv_df.write.mode("overwrite").parquet(silver_path.rsplit('/', 1)[0] + "/customer_ltv")

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read the silver layer data
    silver_df = spark.read.format("delta").load(silver_path)
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id").distinct()).alias("unique_customers"),
            count(col("merchant_id").distinct()).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write the output
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_segments(spark, silver_path, output_path, run_date):
    # Read the silver layer data
    silver_df = spark.read.format("delta").load(silver_path)
    
    # Filter for completed transactions in the last 30 days
    completed_df = silver_df.filter((col("status") == "COMPLETED") & (col("txn_date") >= func.date_sub(run_date, 30)))
    
    # Calculate total spend and transaction frequency per customer
    customer_metrics_df = completed_df.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("txn_frequency")
        )
    
    # Assign segments based on spend
    customer_segments_df = customer_metrics_df.withColumn(
        "segment",
        when(col("total_spent") > 5000, "VIP")
       .when((col("total_spent") >= 1000) & (col("total_spent") <= 5000), "High")
       .when((col("total_spent") >= 200) & (col("total_spent") < 1000), "Mid")
       .otherwise("Low")
    )
    
    # Add segment updated date
    customer_segments_df = customer_segments_df.withColumn("segment_updated_date", lit(run_date))
    
    # Write the output
    customer_segments_df.write.mode("overwrite").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths
    merchant_performance_output_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output_path = f"{silver_path.rsplit('/', 1)[0]}/customer_ltv"
    daily_summary_output_path = f"{gold_output_dir}/daily_summary"
    customer_segments_output_path = f"{gold_output_dir}/customer_segments"
    
    # Run each gold layer function
    build_merchant_performance(spark, silver_path, merchant_performance_output_path, run_date)
    build_customer_ltv(spark, silver_path)
    build_daily_summary(spark, silver_path, daily_summary_output_path, run_date)
    build_customer_segments(spark, silver_path, customer_segments_output_path, run_date)
    
    # Write run metadata
    run_metadata = {
        "run_date": run_date,
        "output_paths": {
            "merchant_performance": merchant_performance_output_path,
            "customer_ltv": customer_ltv_output_path,
            "daily_summary": daily_summary_output_path,
            "customer_segments": customer_segments_output_path
        }
    }
    
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("Customer Segmentation Refresh").getOrCreate()

# Example usage
silver_path = "/path/to/silver_layer"
gold_output_dir = "/path/to/gold_output"
run_date = "2023-10-01"

run_gold(spark, silver_path, gold_output_dir, run_date)
